version: "3"
services:
  api:
    image: findyspaceapi
    container_name: findyspaceapi
    restart: always
    env_file: ./api/.env
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=$NODE_ENV
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/api/
      - ./api/node_modules:/usr/api/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - '3090:3090'
    networks:
      - findyspace
  db:
    container_name: db
    image: postgres:latest
    build:
      context: ./api
      dockerfile: Dockerfile.psql
    ports:
    - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - findyspace

  client:
    image: findyspaceclient
    container_name: findyspaceclient
    restart: always
    stdin_open: true
    tty: true
    env_file: ./client/.env
    environment:
      - NODE_ENV=$NODE_ENV
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/client/
      - ./client/node_modules:/usr/client/node_modules
    depends_on:
      - api
    links:
      - api
    ports:
      - '5090:5090'
    networks:
      - findyspace

  pgadmin:
    links:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - findyspace
 
networks:
  findyspace:
    driver: bridge
