version: "3.8"
services:
  api:
    container_name: api
    restart: always
    env_file: 
      - ./api/.env
    stdin_open: true
    tty: true
    build:
      context: api
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./api:/usr/api/
      - ./api/node_modules:/usr/api/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - findyspace
  db:
    container_name: db
    image: postgres:latest
    build:
      context: ./api
      dockerfile: Dockerfile.psql
    ports:
    - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - findyspace

  client:
    container_name: client
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./client/.env
    build:
      context: client
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./client:/usr/client/
      - ./client/node_modules:/usr/client/node_modules
    depends_on:
      - api
    links:
      - api
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    networks:
      - findyspace

  pgadmin:
    links:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - findyspace
 
networks:
  findyspace:
    driver: bridge
  nginx-proxy-manager_default:
    external: true
