version: "3.8"
services:
  api:
    container_name: api
    image: b0nb0n1/findy-api-${ENVIRONMENT}:${CI_COMMIT}
    restart: always
    env_file: 
      - .env.api
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - findyspace
      - nginx-proxy-manager_default
  db:
    container_name: db
    image: postgres:14
    build:
      context: .
      dockerfile: Dockerfile.psql
    ports:
    - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - findyspace
      - nginx-proxy-manager_default

  client:
    image: b0nb0n1/findy-client-${ENVIRONMENT}:${CI_COMMIT}
    container_name: client
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env.client
    depends_on:
      - api
    links:
      - api
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    networks:
      - findyspace
      - nginx-proxy-manager_default

  pgadmin:
    links:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - findyspace
      - nginx-proxy-manager_default
 
networks:
  findyspace:
    driver: bridge
  nginx-proxy-manager_default:
    external: true
