import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import {
  Box, Button, Grid, TextField, Typography, useMediaQuery,
} from '@mui/material';
import Image from 'next/image';
// eslint-disable-next-line import/no-extraneous-dependencies
import {
  collection,
  deleteDoc,
  doc,
  DocumentData,
  getDocs,
  limit,
  query,
  QueryDocumentSnapshot,
  updateDoc,
  where,
} from '@firebase/firestore';
import firestore from '../src/firebase/clientApp';

function Home() {
  const [waitList, setWaitlist] = useState<QueryDocumentSnapshot<DocumentData>[]>([]);
  const hidden = useMediaQuery((theme: any) => theme.breakpoints.up('sm'));
  const waitListCollection = collection(firestore, 'waitlist');
  const getTodos = async () => {
    const todosQuery = query(waitListCollection, where('email', '==', 'nyabuyabonvic@gmail.com'));
    const querySnapshot = await getDocs(todosQuery);
    console.log('====>', JSON.parse(JSON.stringify(querySnapshot)));
    const result: QueryDocumentSnapshot<DocumentData>[] = [];
    querySnapshot.forEach((snapshot) => {
      result.push(snapshot);
    });

    setWaitlist(result);
  };
  useEffect(() => {
    getTodos();
  }, []);
  console.log(waitList?.[0]?.data?.());
  return (
    <div>
      <Head>
        <title>Findyspace | home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          position: 'relative',
          overflow: 'hidden',
          height: { xs: 'auto', sm: '100vh' },
        }}
      >
        <Box component="header" sx={{ ml: 3, mt: 3 }}>
          <Image width={110} height={25} src="/findyspace.png" />
        </Box>
        {hidden && (
        <Box sx={{
          position: 'absolute',
          right: -412,
          top: -412,
          width: 824,
          height: 824,
          filter: 'blur(10rem)',
          background: 'rgba(242, 121, 86, .95)',
        }}
        />
        )}
        <Grid
          container
          alignItems="center"
          display="flex"
          sx={{
            my: 'auto',
            height: '80%',
            flexDirection: { xs: 'column-reverse', sm: 'row' },
          }}
        >
          <Grid
            item
            xs={12}
            sm={6}
          >
            <Box sx={{
              width: { xs: '90%', sm: '70%' },
              display: 'flex',
              mx: 'auto',
              flexDirection: 'column',
            }}
            >
              <Typography sx={{
                textAlign: { xs: 'center', sm: 'left' },
                fontWeight: 'bold',
                fontSize: { xs: '2rem', sm: '3rem', md: '4rem' },
              }}
              >
                Get Notified When We Launch

              </Typography>
              <Box sx={{
                display: 'flex',
                alignItems: 'center',
                border: '1px solid #E6E6ED',
                height: '48px',
                borderRadius: '20px',
                pl: 2,
                my: 2,
              }}
              >
                <TextField
                  variant="standard"
                  sx={{
                    flexGrow: 1,
                  }}
                  InputProps={{
                    disableUnderline: true,
                  }}
                  placeholder="Enter Your Email Address"
                />
                <Button
                  variant="contained"
                  sx={{
                    mr: 0.5,
                    minWidth: 'max-content',
                    borderRadius: '15px',
                    backgroundColor: '#5D33D5',
                    '&:hover': {
                      backgroundColor: '#5D33D5',
                    },
                  }}
                >
                  Notify Me
                </Button>
              </Box>
              <Typography>Don’t worry, we won’t spam you.</Typography>
            </Box>
          </Grid>
          <Grid item xs={12} sm={6}>
            <Box sx={{
              height: '200px',
              width: '200px',
              background: '#F27956',
              borderRadius: '50%',
              position: 'relative',
              mx: 'auto',
            }}
            >
              <img
                style={{
                  position: 'absolute',
                  right: '-25px',
                  top: '-10px',
                  transform: 'rotate(28deg)',
                  height: '220px',
                  width: '220px',
                }}
                src="/rocket.png"
                alt="rocket launched"
              />
            </Box>
          </Grid>
        </Grid>
      </Box>
    </div>
  );
}

export default Home;
