FROM postgres:14

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-14-postgis-3 -y \
    && apt-get install postgis -y

COPY ./pg-init-scripts/postgis.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
