name: develop

# Controls when the workflow will run
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.X]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd api
          echo "$APIDEV_ENV" >> .env
          cat .env
          yarn install --frozen-lockfile
          yarn lint
        shell: bash
        env:
          APIDEV_ENV: ${{secrets.APIDEV_ENV}}
  
  test-client:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.X]
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - run: |
            cd client
            echo "$CLIENTDEV_ENV_FILE" >> .env
            cat .env
            yarn install --frozen-lockfile
            yarn lint
            yarn build
          shell: bash
          env:
            APIDEV_ENV: ${{secrets.CLIENTDEV_ENV_FILE}}
